# Generated by Django 4.2.2 on 2024-10-09 21:36

from django.db import migrations, models
import django.db.models.deletion
import happyPerformerBackend.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('c_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=30)),
                ('c_addr', models.CharField(default=None, max_length=50, null=True)),
                ('c_phone', models.BigIntegerField()),
                ('add_date', models.CharField(default=None, max_length=200, null=True)),
                ('pay_sts', models.CharField(default=None, max_length=200, null=True)),
                ('payment_type', models.CharField(default=None, max_length=100, null=True)),
                ('start_date', models.TextField(default=None, null=True)),
                ('end_date', models.TextField(default=None, null=True)),
                ('emp_limit', models.IntegerField(default=None, null=True)),
                ('storage_limit', models.IntegerField(default=None, null=True)),
                ('storage_used', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('d_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('d_name', models.CharField(max_length=20)),
                ('add_date', models.CharField(default=None, max_length=200, null=True)),
                ('c_id', models.ForeignKey(db_column='c_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.company')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_name', models.CharField(max_length=30)),
                ('emp_emailid', models.EmailField(default='A@gmail.com', max_length=100, primary_key=True, serialize=False)),
                ('emp_skills', models.CharField(max_length=150)),
                ('emp_role', models.CharField(max_length=100)),
                ('emp_pwd', models.CharField(default='changeme', max_length=100)),
                ('emp_phone', models.CharField(max_length=11)),
                ('emp_profile', models.ImageField(default='profile.png', upload_to='profile/', validators=[happyPerformerBackend.validators.validate_image_extension])),
                ('add_date', models.CharField(default=None, max_length=200, null=True)),
                ('pay_sts', models.CharField(default=None, max_length=200, null=True)),
                ('Status', models.CharField(default='Active', max_length=8)),
                ('likes', models.CharField(default='0', max_length=10000)),
                ('d_id', models.ForeignKey(db_column='d_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.department')),
            ],
        ),
    ]
