# Generated by Django 4.2.2 on 2024-10-09 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_details',
            fields=[
                ('B_Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('holder_name', models.CharField(default=None, max_length=150, null=True)),
                ('bank_name', models.CharField(default=None, max_length=150, null=True)),
                ('acc_no', models.CharField(default=None, max_length=50, null=True)),
                ('branch', models.CharField(default=None, max_length=150, null=True)),
                ('acc_type', models.CharField(default=None, max_length=150, null=True)),
                ('ifsc', models.CharField(default=None, max_length=50, null=True)),
                ('Pan_no', models.CharField(default=None, max_length=50, null=True)),
                ('emp_emailid', models.ForeignKey(db_column='emp_emailid', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='happyPerformerBackend.employee', unique=True)),
            ],
        ),
    ]
