# Generated by Django 4.2.2 on 2024-10-09 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0002_bank_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leavetype',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('LeaveType', models.CharField(max_length=200, null=True)),
                ('Description', models.TextField(null=True)),
                ('Limit', models.IntegerField(default=0)),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='happyPerformerBackend.company')),
            ],
        ),
    ]
