# Generated by Django 4.2.2 on 2024-11-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "happyPerformerBackend",
            "0004_adhoc_admin_log_admintable_ans_static_answer_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Todotasks1",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("completed", models.BooleanField(default=False)),
                (
                    "emp_emailid",
                    models.CharField(default=None, max_length=100, null=True),
                ),
            ],
        ),
    ]
