# Generated by Django 4.2.2 on 2024-11-18 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('happyPerformerBackend', '0005_todotasks1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('rid', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=100)),
                ('emoji', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='happyPerformerBackend.feedback')),
            ],
        ),
    ]
