<<<<<<< HEAD
# Generated by Django 4.2.2 on 2025-02-13 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "happyPerformerBackend",
            "0007_todotasks1_description_todotasks1_end_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="todotasks",
            table="happyPerformerBackend_todotasks",
        ),
    ]
=======
# Generated by Django 4.2.2 on 2025-02-13 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "happyPerformerBackend",
            "0007_todotasks1_description_todotasks1_end_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="todotasks",
            table="happyPerformerBackend_todotasks",
        ),
    ]
>>>>>>> 174a167 (backend1)
