<<<<<<< HEAD
# Generated by Django 4.2.2 on 2025-02-13 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("happyPerformerBackend", "0008_alter_todotasks_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="tid",
            field=models.ForeignKey(
                blank=True,
                db_column="tid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks_tid",
                to="happyPerformerBackend.todotasks1",
            ),
        ),
        migrations.DeleteModel(
            name="Todotasks",
        ),
    ]
=======
# Generated by Django 4.2.2 on 2025-02-13 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("happyPerformerBackend", "0008_alter_todotasks_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="tid",
            field=models.ForeignKey(
                blank=True,
                db_column="tid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks_tid",
                to="happyPerformerBackend.todotasks1",
            ),
        ),
        migrations.DeleteModel(
            name="Todotasks",
        ),
    ]
>>>>>>> 174a167 (backend1)
