<<<<<<< HEAD
# Generated by Django 4.2.2 on 2025-02-13 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("happyPerformerBackend", "0009_alter_tasks_tid_delete_todotasks"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Todotasks1",
            new_name="Todotasks",
        ),
    ]
=======
# Generated by Django 4.2.2 on 2025-02-13 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("happyPerformerBackend", "0009_alter_tasks_tid_delete_todotasks"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Todotasks1",
            new_name="Todotasks",
        ),
    ]
>>>>>>> 174a167 (backend1)
