<<<<<<< HEAD
# Generated by Django 4.2.2 on 2025-02-13 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("happyPerformerBackend", "0010_rename_todotasks1_todotasks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todotasks",
            old_name="id",
            new_name="tid",
        ),
    ]
=======
# Generated by Django 4.2.2 on 2025-02-13 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("happyPerformerBackend", "0010_rename_todotasks1_todotasks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todotasks",
            old_name="id",
            new_name="tid",
        ),
    ]
>>>>>>> 174a167 (backend1)
