<<<<<<< HEAD
# Generated by Django 4.2.2 on 2025-02-14 06:26

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("happyPerformerBackend", "0011_rename_id_todotasks_tid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todotasks",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="todotasks",
            name="start_date",
        ),
        migrations.AddField(
            model_name="todotasks",
            name="date",
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(
                blank=True, null=True
            ),
        ),
    ]
=======
# Generated by Django 4.2.2 on 2025-02-14 06:26

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("happyPerformerBackend", "0011_rename_id_todotasks_tid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todotasks",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="todotasks",
            name="start_date",
        ),
        migrations.AddField(
            model_name="todotasks",
            name="date",
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(
                blank=True, null=True
            ),
        ),
    ]
>>>>>>> 174a167 (backend1)
