<<<<<<< HEAD
# Generated by Django 4.2.2 on 2025-02-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("happyPerformerBackend", "0012_remove_todotasks_end_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kra",
            old_name="KPI",
            new_name="kpi",
        ),
        migrations.RenameField(
            model_name="kra",
            old_name="KRA",
            new_name="kra",
        ),
        migrations.RenameField(
            model_name="kra",
            old_name="Measurement",
            new_name="measurement",
        ),
        migrations.RenameField(
            model_name="kra",
            old_name="ratingsscale",
            new_name="ratings_scale",
        ),
        migrations.RenameField(
            model_name="kra",
            old_name="Target",
            new_name="target",
        ),
        migrations.RenameField(
            model_name="kra",
            old_name="Weightage",
            new_name="weightage",
        ),
        migrations.AlterField(
            model_name="kra",
            name="email_id",
            field=models.EmailField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="kra",
            name="submission_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
=======
# Generated by Django 4.2.2 on 2025-02-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("happyPerformerBackend", "0012_remove_todotasks_end_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kra",
            old_name="KPI",
            new_name="kpi",
        ),
        migrations.RenameField(
            model_name="kra",
            old_name="KRA",
            new_name="kra",
        ),
        migrations.RenameField(
            model_name="kra",
            old_name="Measurement",
            new_name="measurement",
        ),
        migrations.RenameField(
            model_name="kra",
            old_name="ratingsscale",
            new_name="ratings_scale",
        ),
        migrations.RenameField(
            model_name="kra",
            old_name="Target",
            new_name="target",
        ),
        migrations.RenameField(
            model_name="kra",
            old_name="Weightage",
            new_name="weightage",
        ),
        migrations.AlterField(
            model_name="kra",
            name="email_id",
            field=models.EmailField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="kra",
            name="submission_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
>>>>>>> 174a167 (backend1)
