<<<<<<< HEAD
# Generated by Django 4.2.2 on 2025-02-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("happyPerformerBackend", "0014_alter_kra_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kra",
            name="ratings_scale",
            field=models.IntegerField(max_length=500),
        ),
    ]
=======
# Generated by Django 4.2.2 on 2025-02-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("happyPerformerBackend", "0014_alter_kra_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kra",
            name="ratings_scale",
            field=models.IntegerField(max_length=500),
        ),
    ]
>>>>>>> 174a167 (backend1)
