<<<<<<< HEAD
# Generated by Django 4.2.2 on 2025-02-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("happyPerformerBackend", "0016_alter_kra_measurement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kra",
            name="measurement",
            field=models.CharField(default=0, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="kra",
            name="ratings_scale",
            field=models.IntegerField(),
        ),
    ]
=======
# Generated by Django 4.2.2 on 2025-02-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("happyPerformerBackend", "0016_alter_kra_measurement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kra",
            name="measurement",
            field=models.CharField(default=0, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="kra",
            name="ratings_scale",
            field=models.IntegerField(),
        ),
    ]
>>>>>>> 174a167 (backend1)
