<<<<<<< HEAD
# Generated by Django 4.2.2 on 2025-02-20 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("happyPerformerBackend", "0018_alter_attendance_date_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date_updated",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="datetime_log",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="emp_emailid",
            field=models.ForeignKey(
                db_column="emp_emailid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="happyPerformerBackend.employee",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="latitude",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="log_type",
            field=models.CharField(
                blank=True, default="Unknown", max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="longitude",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="user_ip",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
=======
# Generated by Django 4.2.2 on 2025-02-20 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("happyPerformerBackend", "0018_alter_attendance_date_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date_updated",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="datetime_log",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="emp_emailid",
            field=models.ForeignKey(
                db_column="emp_emailid",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="happyPerformerBackend.employee",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="latitude",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="log_type",
            field=models.CharField(
                blank=True, default="Unknown", max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="longitude",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="user_ip",
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
>>>>>>> 174a167 (backend1)
