<<<<<<< HEAD
# Generated by Django 4.2.2 on 2025-02-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("happyPerformerBackend", "0020_alter_kra_kra_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kra",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Pending"),
                    (1, "Approved"),
                    (2, "Rejected"),
                    (3, "Requested"),
                ],
                default=0,
            ),
        ),
    ]
=======
# Generated by Django 4.2.2 on 2025-02-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("happyPerformerBackend", "0020_alter_kra_kra_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kra",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Pending"),
                    (1, "Approved"),
                    (2, "Rejected"),
                    (3, "Requested"),
                ],
                default=0,
            ),
        ),
    ]
>>>>>>> 174a167 (backend1)
